spring:
  application:
    name: zuul
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
server:
  port: 3001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka

zuul:                                     #\u7F51\u5173
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  retryable: true                            #\u5F00\u542F\u91CD\u8BD5 ribbon

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

management:
  endpoints:
    web:
      exposure:
        include:  "*"

turbine:
  app-config: order-service, zuul
  cluster-name-expression: new String("default")